model: gpt-4 # can be gpt-4, llama-2-70b, llama-2-13b, llama-2-7b
dataset: questionintimacy # can be hate-speech, sentiment, ten-dim, analyse-tal
few_shot: 0 # Number of samples to use. 0 means zero-shot classification
wandb_project: crowdsourced_vs_gpt_datasize_v2
wandb_entity: cocoons