model: gpt-4 # can be gpt-3.5-turbo or gpt-4
dataset: empathy#empathy_bin # can be hate-speech, sentiment, ten-dim, analyse-tal
few_shot: 5 # Number of samples to use. 0 means zero-shot classification
wandb_project: crowdsourced_vs_gpt_datasize_v2
wandb_entity: cocoons